version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install bandit
  build:
    commands:
      - echo "Starting Bandit SAST scan..."
      # We removed '-lll' and added '-level HIGH' to be extra strict
      # We removed the output file temporarily to see the error in the console
      - bandit -r . --level HIGH --severity HIGH